import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

export default function Home() {
  const [tamagotchis, setTamagotchis] = useState<any>([]);

  const getTamas = async () => {
    const response = await fetch('http://localhost:8080/tamas');
    const tamas = await response.json();
    return tamas;
  }

  useEffect(() => {
    getTamas()
    .then(tamas => {
        setTamagotchis(tamas);
    })
    .catch((error: any) => {
        console.log(error);
    })

    return function() {}
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row flex-nowrap justify-center items-center">
        <div className="container flex flex-col justify-center items-center">
           {
            tamagotchis.map((tamagotchi) => {
                return (<div className='p-4'>
                    {tamagotchi.id} - {tamagotchi.name} <img srcSet={tamagotchi.img}/> - {tamagotchi.desc} - {tamagotchi.likes}
                </div>)               
            })
           } 
        </div>
      </main>
    </>
  )
}
